language: python
dist: xenial
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.8-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: clpo13
  password:
    secure: du6F8hKk2Gp6pHcKYtJREPT0K1+tg8XOuFNVFHm1FOuJImVEQTonchcpsdbD3zAnQHdOTot8DSZD2/48XTKBYxiBCmxn/imxMyl9trpFMYT8pb1m7s0+6mQmphSHXzu/5VP8WZmN09+TAXuJvMKsRCUXI4KSE2ut3E1hjD3827dYBGcDldzXR0tUJ4JWjKZHOQH+NIv6gFGrJas2dVKNYtwJb9r37Q3XSGQjTwrGthLsa+E3x2bi6IUufNFZEbDJ/y2vP30UkxVtoenbhh5XfR/RDrd33SwwdFOEiWCHxPOTygeTxtz0HA+Io6hLC7f9cOBVYbbMvdlP2YBGEimZR6BaYBDEjwzasy6MqA1dEzxBLtK+xyEsXUl1SWbz1ct/vwnpRNOfNdu8jWnEPyg4/ckFSaoYs8zqU73256yrCjVyHkivTnIMmuZsLcs5pgVxVTc78Nc+zz99TMtm6fZEGMq4OiugbW5UAUPdKqviMYHoXJa6+hLqiWOnXb8gdj7gCznddAt8ooZg3vBAt7knqnt+Y8JI4+HElyF+12O+bdUP3LoGNkdlN7Y839Eg668KYmnF8Uh4A/wdwe5YLLpjq9nc/5VoJ/UvyJxDMjfbdVVrn1huiJ9uKH0gAcfnrJweJjxG5sB4Vq8HXdr4+jsxsxQ6LV2qZsXBY5Tp0QIR0Yc=
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel --universal
  skip_existing: true
