language: python
dist: xenial
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.8-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: clpo13
  password:
    secure: NFTAfdVVNZen8RsUW43Tl3Z/mSme77yGVcTKEmvgEufq5Lz6MlM3gOlZhT6LdqhUcacSvtwYEqtIEjqZIF6PPJmOklxdq2VBqhxioKV0s6lt/NUPs9V6QmYNfZ/7Ae4tPmTeh8c7c6VzlmL8BjKtKXpo92RaAuSa0fJBSwEkxh6zokPUs/XPR8IgTYqLvtwPQyVg05KmSa1+iSI9uAUqbovmjW49dHDPpt4PcE8yAeqwIaW/LsM6YkRoH7kkPHYojW+fxUKz+6njFWbe01K+S2kIwW+8MhFlK3BSVOWOl6zCIBLsTgjSFUhJtc27VtYvmfY666C+TKOystLOU3hjDZ5vb1cHufWShDyWx5bivIMBLhU0cYhXkEZmB7yHu/GPJXeXacTIuN61khRIS2un4o3G3CX8Ta6rxF7z1TLNSmYXLEd6bxER2nBx8Sz9XiYaVY5dhy0h5e//yvZGdcSIFiJ7Z9B/j77+5HfZroQjrT1r5twMkhXlMfBCvGlUWl8B4wsdiN/JF+XExS8+XjJnobaRnM+e4T9zWcRxg4NauRcxgF5sWd/z8rDe77obbnAAW5srlf/5ANxisq1yOlOswTjQcDnZU8HaG184D182kYe9T02IEde07isdKPUUTXUpW5zo2PqAC6Shg98WI25DdmJQOFe2uyDM87CeYayKGkc=
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel --universal
  skip_existing: true
